### ISSUE TITLE
[BUG] JS error in `applicationBlocksEditor.js` and `application.js` on Win 10 setup

### ISSUE THREAD

**Issue by gabriel-glo** [infinum/eightshift-frontend-libs#220]
## Describe the bug

While editing post/page the custom blocks are not showing and there is an error  in console:
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:3788)
    at Module.<anonymous> (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:4043)
    at r (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:12)
    at Object.<anonymous> (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:1548)
    at r (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:12)
    at Object.<anonymous> (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:288)
    at r (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:12)
    at Object.<anonymous> (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:3712)
    at r (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:12)
    at Object.<anonymous> (applicationBlocksEditor-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:1420)
```

Also on frontend there is a similar error in console:
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:122)
    at Module.<anonymous> (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:126)
    at r (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:11)
    at Object.<anonymous> (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:129)
    at r (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:11)
    at Object.<anonymous> (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:166)
    at r (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:11)
    at Object.<anonymous> (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:219)
    at r (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:11)
    at Object.<anonymous> (application-dba2bdc1ab43506a68ec.js?ver=1.0.0:formatted:75)
```

It seems to me that some node_modules package is causing this on Windows 10 machine.
Also there are no errors on webpack build process.

## Steps to Reproduce

1. After successful theme install and asset build, open post/page editor
2. Eightshift blocks are missing in block library
3. Error is in the console

## Your Environment

* PHP version: 7.3.8
* Node version: 10.16
* Development environment: Laravel Homestead v9
* Server type: Nginx
* Operating System and version: Windows 10

**Comment by dingo-d** [comment]
I cannot reproduce this using the develop branch of the frontend libs, so this must have been fixed.

**Comment by gabriel-glo** [comment]
I just did a Windows setup on Laravel Homestead and this is still happening. I used both: 
```
npx create-wp-project
``` 
and 
```
npx create-wp-project --eightshiftLibsBranch="release/3.1.0" --eightshiftFrontendLibsBranch="develop"
```

I got a lot of warnings similar to this one in the terminal:
```
WARNING in ./src/Blocks/custom/columns/components/columns-editor.js 24:23-33
"export 'default' (imported as 'classnames') was not found in 'classnames'
 @ ./src/Blocks/custom/columns/columns-block.js
 @ ./src/Blocks/custom sync -block.js$
 @ ./src/Blocks/assets/scripts/application-blocks-editor.js
 @ ./src/Blocks/assets/application-blocks-editor.js
```

and I tried to change the import of the `classnames` package to what they outlined in the documentation: https://www.npmjs.com/package/classnames, but it didn't help at all. There is still similar issue in eightshift-frontend-libs and other packages:
```
WARNING in ./node_modules/react-select/dist/index-4bd03571.esm.js 1295:9-22
"export 'default' (imported as 'AutosizeInput') was not found in 'react-input-autosize'
 @ ./node_modules/react-select/dist/react-select.esm.js
 @ ./node_modules/@eightshift/frontend-libs/scripts/components/custom-select/custom-select.js
 @ ./node_modules/@eightshift/frontend-libs/scripts/components/index.js
 @ ./src/Blocks/custom/column/components/column-options.js
 @ ./src/Blocks/custom/column/column-block.js
 @ ./src/Blocks/custom sync -block.js$
 @ ./src/Blocks/assets/scripts/application-blocks-editor.js
 @ ./src/Blocks/assets/application-blocks-editor.js

...

WARNING in ./node_modules/@eightshift/frontend-libs/scripts/helpers/responsive-selectors.js 37:9-19
"export 'default' (imported as 'classnames') was not found in 'classnames'
 @ ./node_modules/@eightshift/frontend-libs/scripts/helpers/index.js
 @ ./src/Blocks/assets/scripts/application-blocks.js
 @ ./src/Blocks/assets/application-blocks.js
```

This all results in custom blocks not showing up in the editor because of the above error.

**Comment by dingo-d** [comment]
So this happened when building things through the PowerShell? I didn't get any errors using WSL2, but that's kinda expected since it's linux distro.
I'll try to use PowerShell and see if I can reproduce it.

**Comment by iruzevic** [comment]
fixed
