### ISSUE TITLE
Installation silently fails on PHP 8.1

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#677]
### Describe your bug

When you run the installation on PHP 8.1 you don't get any error out. It just doesn't run.

There should be a clear error on what part failed when the `npx` command is run.

### Steps to Reproduce

1. Have PHP 8.1
2. Try to run `npx create-wp-project`
3. See it fail silently

### Expected behavior

There should be an error message: 

> Your PHP version is not meeting the constraints by the Dev kit. Please use at least PHP 7.4

Or something to that affect

### Environment info

- PHP 8.1
- Mac OS

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by aheissenberger** [comment]
In my case this was related to `composer -v` which did output this message which was interpreted as an error in the check if the composer exists:
```
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
```

The problem is not related to MacOS!

I fixed it with this command line before starting the `npx create-wp-project` command to switch of the logging of xdebug:
`export XDEBUG_CONFIG="log_level=0"`

@iruzevic maybe you can always run `XDEBUG_CONFIG="log_level=0" composer -v` to avoid this error in the check?

**Comment by iruzevic** [comment]
Tnx for the issue, we still don't support php 8. So this could happen. We will check what can we do to fix it

**Comment by aheissenberger** [comment]
I would also suggest to output the error which is related to exiting the setup process. I only found the problem, because I debugged the program.

**Comment by iruzevic** [comment]
this is done in the latest release
